alt_seo_options_default: null
alt_seo_meta_title_default: 'Creo, Boris Strahija'
alt_seo_meta_description_default: 'Boris Strahija, web developer with 20+ years of experience and founder of Creo. I build pixel-perfect websites in PHP, Laravel, WordPress, and dynamic apps with Vue, React, and Svelte'
alt_seo_asset_container: null
alt_seo_collection_asset_containers: {  }
alt_social_options_default: null
alt_seo_social_title_default: 'Creo, Boris Strahija'
alt_seo_social_description_default: 'Boris Strahija, web developer with 20+ years of experience and founder of Creo. I build pixel-perfect websites in PHP, Laravel, WordPress, and dynamic apps with Vue, React, and Svelte'
alt_seo_social_image_default: creo_twitter.jpg
